name: deploy

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: pnpm/action-setup@v2.0.1
              with:
                  version: latest
            - uses: actions/setup-node@v2
              with:
                  cache: 'pnpm'
            - run: pnpm i
            - run: pnpm build
            - uses: JamesIves/github-pages-deploy-action@4.1.8
              with:
                  branch: gh-pages
                  folder: dist
